// DO NOT MODIFY
// Automatically generated by Arkana (https://github.com/rogerluan/arkana)

import Foundation

public protocol GitHubSearchKeysGlobalProtocol {
    var gitHubToken: String { get }
}

public protocol GitHubSearchKeysEnvironmentProtocol {
}
